version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: issue_tracker
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_DATABASE: tracker
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
