import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./theme-config.css";
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import NavBar from "./components/NavBar";
import SessionProvider from "./components/SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Tracker",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.variable}>
        {/* <Theme accentColor="teal" panelBackground="solid"> */}
        <SessionProvider session={session}>
          <Theme>
            <NavBar />
            <main className="p-5">{children}</main>
            {/* <ThemePanel /> */}
          </Theme>
        </SessionProvider>
      </body>
    </html>
  );
}
